name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  deploy-via-sftp:
    needs : build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: 102.219.179.152
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /root/ihebBac
  restart-app :
    needs : deploy-via-sftp
    runs-on: ubuntu-latest
    
    steps :
      - uses: actions/checkout@v3
      - name: run via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: pm2 restart all
          host: 102.219.179.152
          username: root
          password: DxK17976L7Oq?
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    
  
